### ISSUE TITLE
On a deux colonnes colinéaires !

### ISSUE THREAD

**Issue by kevinzagalo** [kevinzagalo/ML-project#7]
j'ai réduit les données à 52 attributs, mais le rang de la matrice des données est de 51,

du coup faut trouver de quelles colonnes il s'agit et en supprimer une!

**Comment by ismailbenki** [comment]
from numpy.linalg import matrix_rank

for col in range(data.shape[1]):
    dt=data.drop([col], axis=1)
    if matrix_rank(dt)==51:
        break
data=data.drop([col], axis=1)

**Comment by ismailbenki** [comment]
je ne l'ai pas testé sur les données à 52 attributs

**Comment by ismailbenki** [comment]
je ne les trouve pas

**Comment by kevinzagalo** [comment]
ok j'ai essayé ton code.

pour les np.array on utilise pas drop mais np.delete ^^

en fait ça vient que quand on rajoute les données wilderness et soil. bizarre..

on laisse tomber la réduction de données et on fait que du test de méthode je pense, 

occupe toi de la méthode QDA. je connais pas mais y a surement des paramètres à faire varier. genre concrètement tu plot le score en fonction des paramètres que tu fais varier
